PinPaymentsSln.Dev/Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PinPaymentsSln.share.Models;
using PinPaymentsSln.share.Services;

namespace PinPaymentsSln.dev.Controllers
{
    public class PlanController : Controller
    {
        private readonly PinPaymentDbContext _context;
        PinService service = new PinService("KZ7j0P1wso3rZTHvspZ-Rg");
        //PinService service = new PinService("U3P9_fpJdgfPI8F9vhagSA");

        public PlanController(PinPaymentDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var plan = service.Plans();
            return View(plan.Response.ToList());
        }

        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            PlanResponse plan = service.Plan(id);
            var subscriberResponse = service.PlanSubscriptions(id);
            foreach (var subscription in subscriberResponse.Response)
            {
                subscription.Customer = service.Customer(subscription.Customer_token);
            }
            plan.Response.Subscriptions = subscriberResponse;

            //var customer = service.Customer(id);
            //Customer customers = customer;

            //Customer customer = service.Customer(id);
            //var subscriberResponses = service.CustomerSubscriptions(id);
            //customer.Subscriptions = subscriberResponses;
            //var customerResponse = service.Customer(subscriberResponse.Response);
            if (plan == null)
            {
                return NotFound();
            }

            return View(plan.Response);
            //return View(customers);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Name, Amount, Currency, Interval, Interval_unit, Intervals, Setup_amount, Trial_amount, Trial_interval, Trial_interval_unit")] PostPlan plans)
        {
            if (ModelState.IsValid)
            {
                service.CreatePlan(plans);
                return RedirectToAction(nameof(Index));
            }
            return View(plans);
        }

        private bool CustomerExists(string id)
        {
            return _context.Customer.Any(e => e.Token == id);
        }
    }
}

PinPaymentsSln.Dev/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PinPaymentsSln.share.Services;
using PinPaymentsSln.share.Models;

namespace PinPaymentsSln.dev.Controllers
{
    public class SubscriptionController : Controller
    {
        private readonly PinPaymentDbContext _context;
        PinService service = new PinService("KZ7j0P1wso3rZTHvspZ-Rg");
        //PinService service = new PinService("U3P9_fpJdgfPI8F9vhagSA");

        public SubscriptionController(PinPaymentDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        // GET: Subscription/Details/5
        public IActionResult Details(string id)
        {
            //Subscription subscrip = new Subscription();
            //subscrip.Token = id;
            //var respSubscription = service.SubscriptionDetails(id);

            if (id == null)
            {
                return NotFound();
            }
            var subscription = service.SubscriptionDetails(id);
            var customer = service.Customer(subscription.Response.Customer_token);
            var plan = service.Plan(subscription.Response.Plan_token);
            var ledgers = service.SubscriptionLedgers(id);
            subscription.Response.Customer = customer;
            subscription.Response.Plan = plan;
            subscription.Response.SubscriptionLedger = ledgers;
            Subscription subscriptions = subscription.Response;

            if (customer == null)
            {
                return NotFound();
            }

            //return View(customer);


            return View(subscriptions);
        }
    }
}

PinPaymentsSln.Dev/Views/Plan/Create.cshtml
@model PinPaymentsSln.share.Models.Plan

@{
    ViewData["Title"] = "Create";
}


<div class="row">
    <div class="col-md-12">
        <h3 class="mb-3">Add New Plan</h3>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Amount" class="control-label"></label>
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Currency" class="control-label"></label>
                        <input asp-for="Currency" class="form-control" />
                        <span asp-validation-for="Currency" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Interval" class="control-label"></label>
                        <input asp-for="Interval" class="form-control" />
                        <span asp-validation-for="Interval" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Interval_unit" class="control-label"></label>
                        <input asp-for="Interval_unit" class="form-control" />
                        <span asp-validation-for="Interval_unit" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Intervals" class="control-label"></label>
                        <input asp-for="Intervals" class="form-control" />
                        <span asp-validation-for="Intervals" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Setup_amount" class="control-label"></label>
                        <input asp-for="Setup_amount" class="form-control" />
                        <span asp-validation-for="Setup_amount" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Trial_amount" class="control-label"></label>
                        <input asp-for="Trial_amount" class="form-control" />
                        <span asp-validation-for="Trial_amount" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Trial_interval" class="control-label"></label>
                        <input asp-for="Trial_interval" class="form-control" />
                        <span asp-validation-for="Trial_interval" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Trial_interval_unit" class="control-label"></label>
                        <input asp-for="Trial_interval_unit" class="form-control" />
                        <span asp-validation-for="Trial_interval_unit" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-success">Add Plan</button>
                </div>
            </div>
            @*<div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>*@
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary mt-3" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PinPaymentsSln.Dev/Views/Plan/Details.cshtml
@model PinPaymentsSln.share.Models.Plan

@{
    ViewData["Title"] = "Details";
}


<div>
    <h3>Plan Details</h3>
    <p class="mt-1 mb-2">
        <a class="btn btn-success" asp-action="Create"><i class="oi oi-plus" style="font-size: 80%;"></i> Add New Plan</a>
    </p>
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-2 p-3" style="background-color: #FAFAFA">
                    <h5 class="text-center text-uppercase">@Html.DisplayFor(model => model.Name)</h5>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-6">
            <div class="card mb-2 p-3" style="background-color: #FAFAFA">
                <h5 class="mb-3"> Pricing Details </h5>
                <dl class="row">
                    <dt class="col-sm-4">
                        @*@Html.DisplayNameFor(model => model.Amount)*@
                        Plan Fee
                    </dt>
                    <dd class="col-sm-8">
                        $@Html.DisplayFor(model => model.Amount)
                        @Html.DisplayFor(model => model.Currency) every
                        @Html.DisplayFor(model => model.Interval)
                        @Html.DisplayFor(model => model.Interval_unit)


                    </dd>
                    <dt class="col-sm-4">
                        @*@Html.DisplayNameFor(model => model.Setup_amount)*@
                        Setup Fee
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Setup_amount)
                    </dd>
                    <dt class="col-sm-4">
                        @*@Html.DisplayNameFor(model => model.Trial_interval)*@
                        Trial Fee
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Setup_amount) for
                        @Html.DisplayFor(model => model.Trial_interval)
                        @Html.DisplayFor(model => model.Trial_interval_unit)
                    </dd>
                </dl>
            </div>
        </div>


        <div class="col-md-6">
            <div class="card mb-2 p-3" style="background-color: #FAFAFA">
                <h5 class="mb-3"> Plan Details </h5>
                <dl class="row">
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Created)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Created)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Token)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Token)
                    </dd>
                </dl>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card mb-2 p-3" style="background-color: #FAFAFA">
                <h5 class="mb-3"> Subscriptions </h5>
                <div class="card">
                    <table class='table'>
                        <thead>
                            <tr style="background-color: #05163d; color: #fff;">
                                <th>Email</th>
                                <th>Token</th>
                                <th>State</th>
                                <th>Next Charge</th>
                                <th></th>
                            </tr>
                        </thead>
                        @foreach (var item in Model.Subscriptions.Response)
                        {
                            <tbody>
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Customer.Email)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Token)</td>
                                    <td>@Html.DisplayFor(modelItem => item.State)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Active_interval_finishes_at)</td>
                                    <td>
                                        <a class="btn btn-warning" asp-controller="Subscription" asp-action="Details" asp-route-id="@item.Token" style="color: #ffffff;">Details</a>
                                    </td>
                                </tr>
                            </tbody>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>



    
</div>
<div>
    <a class="btn btn-primary mt-3" asp-action="Index">Back to List</a>
</div>

PinPaymentsSln.Dev/Views/Plan/Index.cshtml
@model IEnumerable<PinPaymentsSln.share.Models.Plan>

@{
    ViewData["Title"] = "Index";
}

    <h3>Plan List</h3>

<p class="mt-1 mb-2">
    <a class="btn btn-success" asp-action="Create"><i class="oi oi-plus" style="font-size: 80%;"></i> Add New Plan</a>
</p>
<table class='table'>
    <thead>
        <tr style="background-color: #05163d; color: #fff;">
            <th>@Html.DisplayNameFor(model => model.Token)</th>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Amount)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Token)</td>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Amount)</td>
                <td>
                    <a class="btn btn-warning" asp-action="Details" asp-route-id="@item.Token" style="color: #ffffff;"><i class="oi oi-pencil" style="font-size: 80%; color: #ffffff;"></i> Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>